server:
    port: 9000

spring:
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    username: ARQPRODV5
    password: ARQPRODV5
    url: jdbc:oracle:thin:@//141.148.186.198:1621/aqualiadldbs01_pdbprd1.okedatabasesaqu.aquasrvokedevia.oraclevcn.com

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServer2012Dialect