server:
  port: 8080

spring:
  datasource:
    url: jdbc:oracle:thin:@//141.148.186.198:1621/aqualiadldbs01_pdbprd1.okedatabasesaqu.aquasrvokedevia.oraclevcn.com
    username: ARQPRODV5
    password: ARQPRODV5
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.OracleDialect

application:
  request:
    mappings: /api/v1/back-incident-service/incident